Added support for sphinx parallel build
melexis/sphinx-traceability-extension pull request #260
Opened 2022-05-30 12:12 UTC by BenWaumans

Added support for sphinx parallel build to avoid the following warnings:
```
WARNING: the mlx.traceability extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

I'm not sure if there would be any problem with allowing parallel builds in the traceability plugin.

2022-05-30 13:12 UTC, Letme commented
Was this tested on some of the bigger projects? Otherwise, it would be safer to claim we are not...

2022-06-10 07:02 UTC, bavovanachte commented
I've been using it with `-j=auto` for a while now for local builds (not in CI because of the warning and because it's mainly single-core runners). I haven't encountered any issues, but I haven't looked at the actual html results.

I've recently marked sphinx-wavedrom as safe for parallel building. This comment could help: https://github.com/bavovanachte/sphinx-wavedrom/issues/39#issuecomment-995884518

2022-06-10 10:03 UTC, JasperCraeghs commented
I don't think that parallel read is supported. See https://github.com/sphinx-doc/sphinx/pull/9050/files

2022-06-10 10:30 UTC, JasperCraeghs commented
> Based on that even write is not - since we enable changing attributes via callbacks.

I believe that the `traceability_callback_per_item` callback function is called in the event [doctree-read](https://www.sphinx-doc.org/en/master/extdev/appapi.html?highlight=env_before_read_docs#event-doctree-read), which is in the (parallel) read stage. The secondary callback function `traceability_inspect_item` is called in the writing stage but shouldn't/cannot be used to change `env.traceable_collection`. It should only be used to inspect and report warnings. I think that parallel-write may already be supported.

2022-06-10 11:48 UTC, Letme requested changes

2022-06-10 11:48 UTC, Letme commented on mlx/traceability.py
> +        'parallel_read_safe': True,
```suggestion
        'parallel_read_safe': False,
```

2022-06-10 12:57 UTC, Letme approved these changes

2022-06-10 13:47 UTC, JasperCraeghs approved these changes

2022-06-10 13:47 UTC, merged